module Slack
  class EmojiConverter
    MAPPING = {
      "thumbsup" => "👍",
      "+1" => "👍",
      "thumbsdown" => "👎",
      "-1" => "👎",
      "heart" => "❤️",
      "fire" => "🔥",
      "tada" => "🎉",
      "clap" => "👏",
      "100" => "💯",
      "rocket" => "🚀",
      "eyes" => "👀",
      "pray" => "🙏",
      "raised_hands" => "🙌",
      "sparkles" => "✨",
      "star" => "⭐",
      "white_check_mark" => "✅",
      "x" => "❌",
      "thinking_face" => "🤔",
      "laughing" => "😂",
      "joy" => "😂",
      "smile" => "😄",
      "slightly_smiling_face" => "🙂",
      "wink" => "😉",
      "sob" => "😭",
      "cry" => "😢",
      "muscle" => "💪",
      "wave" => "👋",
      "point_up" => "☝️",
      "point_down" => "👇",
      "ok_hand" => "👌",
      "v" => "✌️",
      "metal" => "🤘",
      "call_me_hand" => "🤙",
      "fist" => "✊",
      "punch" => "👊",
      "handshake" => "🤝",
      "hugging_face" => "🤗",
      "rolling_on_the_floor_laughing" => "🤣",
      "upside_down_face" => "🙃",
      "grimacing" => "😬",
      "sweat_smile" => "😅",
      "confused" => "😕",
      "neutral_face" => "😐",
      "expressionless" => "😑",
      "unamused" => "😒",
      "face_with_rolling_eyes" => "🙄",
      "smirk" => "😏",
      "sunglasses" => "😎",
      "nerd_face" => "🤓",
      "warning" => "⚠️",
      "boom" => "💥",
      "zap" => "⚡",
      "bulb" => "💡",
      "memo" => "📝",
      "bell" => "🔔",
      "link" => "🔗",
      "lock" => "🔒",
      "key" => "🔑",
      "mag" => "🔍",
      "gear" => "⚙️",
      "wrench" => "🔧",
      "hammer" => "🔨",
      "construction" => "🚧",
      "package" => "📦",
      "gift" => "🎁",
      "balloon" => "🎈",
      "confetti_ball" => "🎊",
      "trophy" => "🏆",
      "medal" => "🏅",
      "crown" => "👑",
      "gem" => "💎",
      "moneybag" => "💰",
      "chart_with_upwards_trend" => "📈",
      "chart_with_downwards_trend" => "📉",
      "coffee" => "☕",
      "beer" => "🍺",
      "pizza" => "🍕",
      "hamburger" => "🍔",
      "fries" => "🍟",
      "popcorn" => "🍿",
      "cake" => "🎂",
      "cookie" => "🍪",
      "apple" => "🍎",
      "lemon" => "🍋",
      "avocado" => "🥑",
      "dog" => "🐕",
      "cat" => "🐈",
      "unicorn" => "🦄",
      "rainbow" => "🌈",
      "sunny" => "☀️",
      "cloud" => "☁️",
      "snowflake" => "❄️",
      "ocean" => "🌊",
      "earth_americas" => "🌎"
    }.freeze

    DEFAULT_EMOJI = "👍"

    def self.convert(slack_emoji)
      MAPPING[slack_emoji] || DEFAULT_EMOJI
    end
  end
end
